show databases;

use chandrucafe;

show tables;

drop table contacts;

-- UNIQUE CONSTRAINTS

create table contacts(
	name varchar(20) not null,
    phone varchar(15) not null unique
);

insert into contacts(name,phone)
values ('Chandru','12345');

insert into contacts(name,phone)
values ('Razeth','12345');

select * from contacts;

insert into contacts(name,phone)
values ('Kadhirvel','92345');

select * from contacts;

-- CHECK CONSTRAINTS

CREATE TABLE USERS(
	USERNAME VARCHAR (20) NOT NULL,
    AGE INT CHECK(AGE>18)
);

SHOW TABLES;

INSERT INTO USERS (USERNAME,AGE)
VALUES ('KAVITHA',25);

INSERT INTO USERS (USERNAME,AGE)
VALUES ('RUPINI',25);

INSERT INTO USERS (USERNAME,AGE)
VALUES ('VISHALI',-9);

CREATE TABLE PALINDROME(
	WORD VARCHAR(50) CHECK(REVERSE(WORD) = WORD)
    );
    
INSERT INTO PALINDROME(WORD)
VALUES('MOM');

INSERT INTO PALINDROME(WORD)
VALUES('RACECAR');

INSERT INTO PALINDROME(WORD)
VALUES('CHANDRU');

INSERT INTO PALINDROME(WORD)
VALUES('MOMMY');

SHOW TABLES;

SELECT * FROM USERS;

-- NAMED CONSTRAINTS

CREATE TABLE USERS2(
USERNAME VARCHAR(20) NOT NULL,
AGE INT,
CONSTRAINT AGE_NOT_NEGATIVE CHECK (AGE>=0)
);
INSERT INTO USERS2(USERNAME,AGE)
VALUES('MUTTON',-7);

CREATE TABLE PALINDROMES(
	WORD VARCHAR(50),
    CONSTRAINT WORD_IS_PALINDROME CHECK (REVERSE(WORD) = WORD)
    );
    
INSERT INTO PALINDROMES(WORD)
VALUES('MOM');

INSERT INTO PALINDROME(WORD)
VALUES('MOMMO');

-- MULTIPLE COLUMN CONSTRAINTS

CREATE TABLE COMPANIES(
NAME VARCHAR(255) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
CONSTRAINT NAME_ADDRESS UNIQUE (NAME,ADDRESS)
);

INSERT INTO COMPANIES(NAME,ADDRESS)
VALUES('BATMAN','12 NY USA'),
	('SPIDERMAN','43 CN UK');
    
INSERT INTO COMPANIES(NAME,ADDRESS)
VALUES('SPIDERMAN','43 CN USA');

SELECT * FROM COMPANIES;

INSERT INTO COMPANIES(NAME,ADDRESS)
VALUES('CHANDRU','12 NEYVELI');

CREATE TABLE HOUSES(
PURCHASE_PRICE INT NOT NULL,
SALE_PRICE INT NOT NULL,
CONSTRAINT SALE_PRICE_GT_PPRICE CHECK(SALE_PRICE >= PURCHASE_PRICE)
);


INSERT INTO HOUSES(PURCHASE_PRICE,SALE_PRICE)
VALUES (100,200);

INSERT INTO HOUSES(PURCHASE_PRICE,SALE_PRICE)
VALUES (500,499);

-- ALTER TABLE

SELECT * FROM COMPANIES;

ALTER TABLE COMPANIES
ADD COLUMN PHONE VARCHAR(15);

SELECT * FROM COMPANIES;

ALTER TABLE COMPANIES
ADD COLUMN PHONE VARCHAR(15) NOT NULL;

ALTER TABLE COMPANIES
ADD COLUMN EMPLOYEE_COUNT INT NOT NULL default 1;

SELECT * FROM COMPANIES;

-- ALTER DROP COLUMNS

ALTER TABLE COMPANIES DROP COLUMN PHONE;

ALTER TABLE COMPANIES DROP COLUMN EMPLOYEE_COUNT;

RENAME TABLE COMPANIES TO SUPPLIERS;

SELECT * FROM SUPPLIERS;

ALTER TABLE SUPPLIERS RENAME TO COMPANIES;

SELECT * FROM COMPANIES;

ALTER TABLE COMPANIES
RENAME COLUMN NAME TO EMPLOYEE_NAME;

-- MODIFYING EXISTING COLUMN DEFINITION

SELECT * FROM COMPANIES;

SHOW TABLES;

DESC COMPANIES;

ALTER TABLE COMPANIES modify EMPLOYEE_NAME VARCHAR(100) default 'UNKNOWN';

DESC COMPANIES;

INSERT INTO COMPANIES(ADDRESS)
VALUES ('2 ROME PARIS');

SELECT * FROM COMPANIES;

SELECT * FROM HOUSES;

ALTER TABLE houses 
ADD CONSTRAINT positive_pprice CHECK (purchase_price >= 0);

INSERT INTO HOUSES(PURCHASE_PRICE, SALE_PRICE) VALUES(-1,4);

SELECT * FROM HOUSES;

ALTER TABLE houses DROP CONSTRAINT positive_pprice;
