SELECT 10 != 10;

SELECT 15 >14 AND 99-5 < 94;

SELECT 1 IN (5,3) OR 9 BETWEEN 8 AND 10;

SELECT * FROM BOOKS
WHERE RELEASED_YEAR >1980;

SELECT * FROM BOOKS
WHERE AUTHOR_LNAME = 'EGGERS' or AUTHOR_LNAME = 'CHABON';

SELECT * FROM BOOKS WHERE AUTHOR_LNAME = 'LAHIRI' AND RELEASED_YEAR > 2000;

SELECT * FROM BOOKS WHERE PAGES BETWEEN 100 AND 200;

SELECT * FROM BOOKS WHERE AUTHOR_LNAME LIKE 'C%' or 'S%';

SELECT AUTHOR_LNAME, SUBSTR(AUTHOR_LNAME,1,1) FROM BOOKS;

SELECT TITLE, AUTHOR_LNAME FROM BOOKS WHERE SUBSTR(AUTHOR_LNAME,1,1) IN ('C','S') ;

SELECT TITLE, AUTHOR_LNAME, 
CASE
WHEN TITLE LIKE '%STORIES%'THEN '%SHORT STORIES%'
WHEN TITLE LIKE "%JUST KIDS%" OR TITLE = 'A HEARTBREAKING WORK OF STAGGERING GENIUS' THEN 'MEMIOR' 
ELSE 'NOVEL'
END AS TYPE
FROM BOOKS;

SELECT CONCAT(AUTHOR_FNAME,' ',AUTHOR_LNAME) AS AUTHOR,
CASE
WHEN COUNT(*) = 1 THEN '1 BOOK'
ELSE 'MULTIPLE BOOKS'
END AS COUNT
FROM BOOKS
WHERE AUTHOR IS NOT NULL
GROUP BY AUTHOR; 


SET SQL_SAFE_UPDATES = 0;

SELECT AUTHOR_FNAME,AUTHOR_LNAME,
CASE
WHEN COUNT(*) = 1 THEN '1 BOOK'
ELSE 'MULTIPLE BOOKS'
END AS COUNT
FROM BOOKS
WHERE AUTHOR_LNAME IS NOT NULL
GROUP BY AUTHOR_FNAME,AUTHOR_LNAME; 

SELECT CONCAT(AUTHOR_FNAME,' ',AUTHOR_LNAME) AS AUTHOR,
CASE
WHEN COUNT(*) = 1 THEN '1 BOOK'
ELSE CONCAT(COUNT(*),' BOOKS')
END AS COUNT
FROM BOOKS
WHERE AUTHOR_LNAME IS NOT NULL AND AUTHOR_FNAME IS NOT NULL
GROUP BY AUTHOR_FNAME,AUTHOR_LNAME; 

